// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdaac_Gv2kgOzOE1IZUSTJ2tFkoOKGz7U',
    appId: '1:1038627422972:web:6b5242bc5f010842e64d79',
    messagingSenderId: '1038627422972',
    projectId: 'tik-tok-207c6',
    authDomain: 'tik-tok-207c6.firebaseapp.com',
    storageBucket: 'tik-tok-207c6.firebasestorage.app',
    measurementId: 'G-9JV087Q2T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdyeDu1ZmesPlnWKV5mef0p-B7FseJvSE',
    appId: '1:1038627422972:android:7f2d8aead96ea5e5e64d79',
    messagingSenderId: '1038627422972',
    projectId: 'tik-tok-207c6',
    storageBucket: 'tik-tok-207c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHbJhZCLEYV5uZJqAwPYgfdMwkR0_OxBY',
    appId: '1:1038627422972:ios:a15f1e9529a4a8a2e64d79',
    messagingSenderId: '1038627422972',
    projectId: 'tik-tok-207c6',
    storageBucket: 'tik-tok-207c6.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHbJhZCLEYV5uZJqAwPYgfdMwkR0_OxBY',
    appId: '1:1038627422972:ios:a15f1e9529a4a8a2e64d79',
    messagingSenderId: '1038627422972',
    projectId: 'tik-tok-207c6',
    storageBucket: 'tik-tok-207c6.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdaac_Gv2kgOzOE1IZUSTJ2tFkoOKGz7U',
    appId: '1:1038627422972:web:238ca86e5d9aa9dfe64d79',
    messagingSenderId: '1038627422972',
    projectId: 'tik-tok-207c6',
    authDomain: 'tik-tok-207c6.firebaseapp.com',
    storageBucket: 'tik-tok-207c6.firebasestorage.app',
    measurementId: 'G-9S5R7ZBW76',
  );

}